language: python
python:
- '3.6.6'
install:
- pip install -r requirements_dev.txt
script:
- flake8  --exclude=migrations
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: FYdvcr6tNKTVGa+t+R6bIoUCE1ovKcC8Al3L19i6iVcAC8LQA+0sWGpZ0Gp8Ise+hW9FXfvxWnBXDBA6dvndxK4tazUS5Un85+mn4cFWj2Wjtn7kBr+JJ41oKmdLDRa8UMxMgHrrZJLVPzU7Aj4ts9Xuki6J4CTlsp5IshVTlcpasUeG1lZQuyQTQOuccFpw1RThQNriWQX6u0YSu9PCn/8hFu92BysOYY70syQ0AtVTFR+63tXCKhW818SAI5jN492lplwE+W+oCkzTbQQaeNwYpq2GP1MabpLELez3lZXlR1p76h4chHmszR41hSe8YhYXGxSXLnpqXQUiSJolA1TEQbPcSIBF8sbfke9fkYogi8WNFYiJCHjRGaoxFl7xQWt/Aq8orbAudl0UhWxxZE0HQxubl/ccB9VGmxXxcvJg2XpXdJLnAnNk2KqdLrcgE4goOwMCdxBBXJP2FDj1EitwO2SpziRi/sxFC499ShZNZ/QyjqP5bJFPwBX4inGvmwqN+dC6kqS1har7Q3VtTXxo34eZQnu4AohH2jlWR9/WpMSsiG0b31ktuz6UZPl+4kpewue39Qw2DMAr0A6aOdtekn4Z/H5IMUoLCUqNVcpJ7CeWgq9mhjAetZqOg6B8WChx7wYpKa6S0nB0ynVguZLPu0oVV0WUK+NnFQby+Yg=
  app: thundersnow-v3
