"""empty message

Revision ID: 8a91f2b579e9
Revises: 
Create Date: 2018-04-16 16:04:38.625198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a91f2b579e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('entered_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'payments', 'users', ['entered_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_column('payments', 'entered_by')
    # ### end Alembic commands ###
